on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node_version: ['8', '10', '12']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Markup Link Checker (mlc)
      # You may pin to the exact commit or the version.
      # uses: becheran/mlc@167bf1b19ffed2e5a3f31770ec1046e302d592fb
      - uses: becheran/mlc@v0.16.1
        with:
          # arguments
          args: ./ # optional, default is ./
